apiVersion: v1
kind: ReplicationController
metadata:
  name: first-kafka
spec:
  replicas: 1
  selector:
    kafka: first
  template:
    metadata:
      labels:
        kafka: first
    spec:
      hostNetwork: true
      containers:
        - image: asad26/rpi-zookeeper:version4
          name: zookeeper-1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /zk-start.sh 1
          ports:
            - containerPort: 2181
              #hostPort: 2181
              name: clientport
        - image: asad26/rpi-kafka9-final:version7
          name: kafka-broker-1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /1kafka-start.sh 1
          ports:
            - containerPort: 9092
              #hostPort: 9092
              name: brokerport
          volumeMounts:
            - name: motionpics
              mountPath: /camera1
      restartPolicy: Always
      nodeSelector:
        name: rpi-master-1
      volumes:
        - hostPath:
            path: /mnt/camera1
          name: motionpics
