apiVersion: v1
kind: ReplicationController
metadata:
  name: fourth-kafka
spec:
  replicas: 1
  selector:
    kafka: fourth
  template:
    metadata:
      labels:
        kafka: fourth
    spec:
      hostNetwork: true
      containers:
        - image: asad26/rpi-zookeeper:version4
          name: zookeeper-4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /zk-start.sh 4
          ports:
            - containerPort: 2181
              #hostPort: 2181
              name: clientport
        - image: asad26/rpi-kafka9-final:version7
          name: kafka-broker-4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /4kafka-start.sh 4
          ports:
            - containerPort: 9092
              #hostPort: 9092
              name: brokerport
          volumeMounts:
            - name: motionpics
              mountPath: /camera4
      restartPolicy: Always
      nodeSelector:
        name: rpi-node-1
      volumes:
        - hostPath:
            path: /mnt/camera4
          name: motionpics
