apiVersion: v1
kind: ReplicationController
metadata:
  name: third-kafka
spec:
  replicas: 1
  selector:
    kafka: third
  template:
    metadata:
      labels:
        kafka: third
    spec:
      hostNetwork: true
      containers:
        - image: asad26/rpi-zookeeper:version4
          name: zookeeper-3
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /zk-start.sh 3
          ports:
            - containerPort: 2181
              #hostPort: 2181
              name: clientport
        - image: asad26/rpi-kafka9-final:version7
          name: kafka-broker-3
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - /3kafka-start.sh 3
          ports:
            - containerPort: 9092
              #hostPort: 9092
              name: brokerport
          volumeMounts:
            - name: motionpics
              mountPath: /camera3
      restartPolicy: Always
      nodeSelector:
        name: rpi-master-3
      volumes:
        - hostPath:
            path: /mnt/camera3
          name: motionpics
